apiVersion: v1
kind: ConfigMap
metadata:
  name: email-templates
data:
  inactive_warning.tmpl: |
    Subject: You are about to be inactive
    BCC:
    - seniorstaff@vzanartcc.net
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This is a warning that you have not yet controlled the minimum number of hours during the activity as
      required by the Anchorage ARTCC Facility Administrative Policy.  Per the policy, controllers must control 
      no less than 2 hours per 2 month period.</p>

      <p>If, one the first of the month, this requirement is not met, you will be marked inactive and are subject to
      removal from the roster. If you are unable to meet this requirement, please contact the Senior Staff to request
      a leave of absense. They may be contacted by emailing seniorstaff@vzanartcc.net.</p>

      <p>Thanks,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Anchorage ARTCC, VATUSA<br>
      https://www.vzanartcc.net</p>
  inactive.tmpl: |
    Subject: You are inactive
    BCC:
    - seniorstaff@vzanartcc.net
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This is an email notification to inform you that you have not met the minimum activity requirements as set forth
      by the Anchorage ARTCC Facility Administrative Policy.  Per the policy, controllers must control no less than 2
      hours per 2 month period. You have been marked inactive on the roster and are subject to removal for Inactivity.</p>

      <p>If you require a Leave of Absense, please contact the Senior Staff as soon as possible. They may be contacted by
      emailing seniorstaff@vzanartcc.net.</p>

      <p>Thanks,<br>
      {{- range $atm := findRole "atm" -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Anchorage ARTCC, VATUSA<br>
      https://www.vzanartcc.net</p>
  visiting_rejected.tmpl: |
    Subject: Your visiting controller request has been rejected
    BCC:
    - seniorstaff@vzanartcc.net
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This email is to notify you that your request to join the Anchorage ARTCC Visiting Controller Roster has been
      rejected. If you feel this was done in error, please reach out to the Anchorage ARTCC Senior Staff by emailing
      seniorstaff@vzanartcc.net.</p>

      <p>The general reason applications are rejected are due to you not meeting the minimum requirements as listed on the
      website.</p>

      <p>Regards,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Anchorage ARTCC, VATUSA<br>
      https://www.vzanartcc.net</p>
  visiting_added.tmpl: |
    Subject: You have been added to the visiting controller roster
    BCC:
    - seniorstaff@vzanartcc.net
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This email is to notify you that you have been added to the Anchorage ARTCC Visiting Controller Roster. Firstly,
      welcome to the last frontier. Anchorage ARTCC is the largest ARTCC in VATUSA, featuring an airspace that stretches
      over 2 million square miles and features everything from the Fjords of the Pacific Northwest, to the frozen tundra,
      to the Aleutian Islands. We are excited to have you join us and look forward to seeing you on the scopes.</p>

      <p>To begin, please join the Anchorage ARTCC Discord if you have not already. You may join it and link your account through
      our Discord Portal, accessible at https://discord.vzanartcc.net.</p>

      <p>Next, please review the Anchorage ARTCC Policies by visiting our website at https://www.vzanartcc.net.</p>

      <p>Lastly, when you are ready, please visit the "request-training" Discord channel to begin your visitor checkout.</p>

      <p>We look forward to controlling with you and hope to see you soon!<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Anchorage ARTCC, VATUSA<br>
      https://www.vzanartcc.net</p>
  visiting_removed.tmpl: |
    Subject: You have been removed from the visiting controller roster
    BCC:
    - seniorstaff@vzanartcc.net
    Body: |
      Dear {{.FirstName}} {{.LastName}}

      <p>This is notification that you have been removed from the Anchorage ARTCC Visiting Controller Roster. If you feel this
      was done in error, please reach out to the Anchorage ARTCC Senior Staff by emailing seniorstaff@vzanartcc.net.</p>

      <p>Regards,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Anchorage ARTCC, VATUSA<br>
      https://www.vzanartcc.net</p>
